import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/Header";

const jetbrainsMono = JetBrains_Mono({
	variable: "--font-jetbrains-mono",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${jetbrainsMono.variable} antialiased bg-[#202020]`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
