import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import localFont from 'next/font/local';

const IntroFont = localFont({
  src: "../../public/Intro.ttf"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${IntroFont.className} dark antialiased bg-[#202020]`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
